name: ttnode

on:
  push:

jobs:
  docker:
    uses: WaterLemons2k/Docker/.github/workflows/docker.yml@main
    with:
      tags: |
        waterlemons2k/ttnode
        waterlemons2k/ttnode:v1.0.0.384
    secrets:
      TOKEN: ${{ secrets.TOKEN }}